version: "3"
services:
  influxdb:
    image: influxdb:2.4-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - C:\docker-vol\influxdb2\data:/var/lib/influxdb2:rw
      - C:\docker-vol\influxdb2\config:/etc/influxdb2:rw
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.4-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - C:\docker-vol\influxdb2\data:/var/lib/influxdb2:rw
      - C:\dev\docker\influxv2\entrypoint.sh:/entrypoint.sh:rw
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment:
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=shbaek
      - DOCKER_INFLUXDB_INIT_PASSWORD=tmdghkqor0
      - DOCKER_INFLUXDB_INIT_ORG=cn
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      # - INFLUXDB_HTTP_AUTH_ENABLED=false
      # - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      # - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    # entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:1.24-alpine
    links:
      - influxdb
    volumes:
      #  Sync timezone with host
      # - /etc/localtime:/etc/localtime:ro
      # Mount for telegraf config
      - C:\docker-vol\telegraf\telegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - ./influxv2.env
    environment:
      - DOCKER_INFLUXDB_INIT_URLS=http://influxv2_influxdb_1:8086
      - DOCKER_INFLUXDB_INIT_ORG=cn
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    depends_on:
      - influxdb_cli
volumes:
  influxdb2:
